-- MEYLEPDP-531 => MEYLEPDP-542
-- Erweiterung von Komponenten um Komponentenbestandteile
CREATE TABLE public.DEVA_KOMPONENTE_BESTANDTEIL
(
  ID bigserial NOT NULL,
  VERSION bigint,
  ANZAHL bigint NOT NULL,
  HINWEIS character varying(100) NOT NULL,
  KOMPONENTE bigint NOT NULL,
  KOMPONENTE_BESTANDTEIL bigint NOT NULL,
  primary key (ID)
);

ALTER TABLE public.DEVA_KOMPONENTE_BESTANDTEIL
  ADD CONSTRAINT fke8ae041b8d6ce006
  FOREIGN KEY (KOMPONENTE)
  REFERENCES public.DEVA_KOMPONENTE;

ALTER TABLE public.DEVA_KOMPONENTE_BESTANDTEIL
  ADD CONSTRAINT fke8ae041bf69c798e
  FOREIGN KEY (KOMPONENTE_BESTANDTEIL)
  REFERENCES public.DEVA_KOMPONENTE;

ALTER TABLE public.DEVA_KOMPONENTE_BESTANDTEIL OWNER TO meyle;

-- Setze abgeleiteten Ampelstatus auf 0 = grau.
ALTER TABLE public.DEVA_KOMPONENTE ADD AMPEL_STATUS character varying(255) NOT NULL DEFAULT 'GRAU';