ALTER TABLE DEVA_ARTIKEL_ZINFO DROP CONSTRAINT "FKB2FEFC027FFED7F4";

ALTER TABLE DEVA_ARTIKEL_V DROP CONSTRAINT "FK1B1969507FFED7F4";

ALTER TABLE DEVA_ARTIKEL_KOMPONENTE DROP CONSTRAINT "FK5B3E08463D3B7A12";

ALTER TABLE DEVA_ARTIKEL_BESTANDTEIL DROP CONSTRAINT "FK7A16C7A1F093319A";

ALTER TABLE DEVA_ARTIKEL DROP CONSTRAINT "FK6E9467B98C8FC63D";

ALTER TABLE DEVA_ARTIKEL_ZUBEHOER DROP CONSTRAINT "FK5D10F7783D3B7A12";

ALTER TABLE DEVA_ARTIKEL_FAHRZEUGE DROP CONSTRAINT "FKE6AB83FD7FFED7F4";

ALTER TABLE DEVA_ARTIKEL_BESTANDTEIL DROP CONSTRAINT "FK7A16C7A13D3B7A12";

ALTER TABLE DEVA_ARTIKEL_DOKUMENTE DROP CONSTRAINT "FKF8D0B8C7FFED7F4";

ALTER TABLE DEVA_ARTIKEL_KOMMENTAR DROP CONSTRAINT "FK792535B27FFED7F4";

ALTER TABLE DEVA_ARTIKEL_LOGBUCH DROP CONSTRAINT "FK147182967FFED7F4";

ALTER TABLE DEVA_KOMPONENTE_ZINFO DROP CONSTRAINT "FKC0F39BFCDFA2B9C0";

ALTER TABLE DEVA_ARTIKEL_KOMPONENTE DROP CONSTRAINT "FK5B3E08468D6CE006";

ALTER TABLE DEVA_KOMPONENTE_LOGBUCH DROP CONSTRAINT "FK77BE0C10DFA2B9C0";

ALTER TABLE DEVA_KOMPONENTE_KOMMENTAR DROP CONSTRAINT "FK3B7548ACDFA2B9C0";

ALTER TABLE DEVA_KOMPONENTE_V DROP CONSTRAINT "FKEF01164ADFA2B9C0";

ALTER TABLE DEVA_KOMPONENTE_DOKUMENTE DROP CONSTRAINT "FKD1DD1E86DFA2B9C0";

ALTER TABLE JBPM_PA_STAKEHOLDERS DROP CONSTRAINT "FK8CEAD01136B2F154";

ALTER TABLE JBPM_I18NTEXT DROP CONSTRAINT "FK17E9841598B62B";

ALTER TABLE JBPM_PA_RECIPIENTS DROP CONSTRAINT "FKB9FACEFE36B2F154";

ALTER TABLE JBPM_PA_EXCLOWNERS DROP CONSTRAINT "FKF11B650036B2F154";

ALTER TABLE JBPM_PA_BAS DROP CONSTRAINT "FKC6DBDAF036B2F154";

ALTER TABLE JBPM_PA_POTOWNERS DROP CONSTRAINT "FK279A009136B2F154";

ALTER TABLE JBPM_TASK_COMMENT DROP CONSTRAINT "FKE7D49C4FB35E68F5";

ALTER TABLE JBPM_DEADLINE DROP CONSTRAINT "FK414B622227ABEB8A";

ALTER TABLE JBPM_ATTACHMENT DROP CONSTRAINT "FKF6BB126DF21826D9";

ALTER TABLE JBPM_I18NTEXT DROP CONSTRAINT "FK17E98415B2FA6B18";

ALTER TABLE JBPM_I18NTEXT DROP CONSTRAINT "FK17E9841569B21EE8";

ALTER TABLE JBPM_DELEGATION_DELEGATES DROP CONSTRAINT "FK4E75DE136B2F154";

ALTER TABLE JBPM_SUBTASKSSTRATEGY DROP CONSTRAINT "FK9D95288B36B2F154";

ALTER TABLE JBPM_DEADLINE DROP CONSTRAINT "FK414B6222684BACA3";

ALTER TABLE DEVA_ARTIKEL DROP CONSTRAINT "FK6E9467B96B6C33BF";

ALTER TABLE DEVA_KOMPONENTE DROP CONSTRAINT "FKB8970B334E705A2C";

ALTER TABLE DEVA_PROZESS_SCHRITT DROP CONSTRAINT "FK7CF7493511000A0A";

ALTER TABLE DEVA_PROZESS_SCHRITT DROP CONSTRAINT "FK7CF74935199FC6F5";

ALTER TABLE DEVA_BONUSZEIT DROP CONSTRAINT "FK4F4940821123A3E4";

ALTER TABLE DEVA_PROZESS DROP CONSTRAINT "FK87D3108562008C47";

ALTER TABLE JBPM_I18NTEXT DROP CONSTRAINT "FK17E984155EEBB6D9";

ALTER TABLE JBPM_RA_POTOWNERS DROP CONSTRAINT "FK36FD4B4FE17E130F";

ALTER TABLE JBPM_NOTIFICATION DROP CONSTRAINT "FKAD3513B53E0890B";

ALTER TABLE JBPM_BOOLEAN_EXPRESSION DROP CONSTRAINT "FKA4A3EA79AFB75F7D";

ALTER TABLE JBPM_EMAIL_NOT DROP CONSTRAINT "FKAD3513B53E0890BC400F4E6";

ALTER TABLE JBPM_REASSIGNMENT DROP CONSTRAINT "FKF23C3C0AA5C17EE0";

ALTER TABLE JBPM_I18NTEXT DROP CONSTRAINT "FK17E984153330F6D9";

ALTER TABLE JBPM_ESCALATION DROP CONSTRAINT "FK5CA4A3DFC7A04C70";

ALTER TABLE DEVA_BPMNDEFINITION DROP CONSTRAINT "FKA6CA9AB5CBFA49B5";

ALTER TABLE DEVA_PROZESS DROP CONSTRAINT "FK87D31085EB1C5F20";

ALTER TABLE DEVA_BEZEICHNUNG_ARTIKEL DROP CONSTRAINT "FK2477D5BA2525EA1E";

ALTER TABLE DEVA_BENUTZER_PRODUKTGRUPPE DROP CONSTRAINT "FK3133F1B32525EA1E";

ALTER TABLE DEVA_PRODUKTGRUPPE DROP CONSTRAINT "FKB68B59AF748E0737";

ALTER TABLE DEVA_KOMPONENTE DROP CONSTRAINT "FKB8970B33A1CBFC4";

ALTER TABLE DEVA_ARTIKEL_DOKUMENTE DROP CONSTRAINT "FKF8D0B8CFE056660";

ALTER TABLE DEVA_ARTIKEL DROP CONSTRAINT "FK6E9467B9A1CBFC4";

ALTER TABLE DEVA_KOMPONENTE_DOKUMENTE DROP CONSTRAINT "FKD1DD1E86FE056660";

ALTER TABLE JBPM_EMAIL_NOT_HEAD DROP CONSTRAINT "FKA84EA99943454A01";

ALTER TABLE DEVA_ARTIKEL_ZINFO DROP CONSTRAINT "FKB2FEFC0246B7FC54";

ALTER TABLE DEVA_KOMPONENTE_ZINFO DROP CONSTRAINT "FKC0F39BFC46B7FC54";

ALTER TABLE DEVA_ARTIKEL_ZUBEHOER DROP CONSTRAINT "FK5D10F778B3B24CEA";

ALTER TABLE DEVA_SOLLZEITEN_KLASSIFIKATION DROP CONSTRAINT "FK8E4EE667C589307F";

ALTER TABLE DEVA_FIRMA_SOLLZEITEN_A DROP CONSTRAINT "FK7CBC0ECC74E70772";

ALTER TABLE DEVA_FIRMA_SOLLZEITEN_K DROP CONSTRAINT "FK7CBC0ED6B3DE8E56";

ALTER TABLE DEVA_SOLLZEIT_WDH_K DROP CONSTRAINT "FK201F1BCDC589307F";

ALTER TABLE DEVA_BPMN_DEFINITION_THN DROP CONSTRAINT "FK56CC356B3EBDB8FE";

ALTER TABLE DEVA_PROZESS DROP CONSTRAINT "FK87D31085975A806A";

ALTER TABLE DEVA_UEBERSETZUNG_ARTIKEL DROP CONSTRAINT "FK51C371F7EACC69FA";

ALTER TABLE DEVA_ARTIKEL DROP CONSTRAINT "FK6E9467B92325AC4E";

ALTER TABLE DEVA_KOMPONENTE_V DROP CONSTRAINT "FKEF01164AB2657C32";

ALTER TABLE DEVA_BENUTZER_PRODUKTGRUPPE DROP CONSTRAINT "FK3133F1B3DC74F062";

ALTER TABLE DEVA_KOMPONENTE_LOGBUCH DROP CONSTRAINT "FK77BE0C10DC74F062";

ALTER TABLE DEVA_ARTIKEL DROP CONSTRAINT "FK6E9467B98C57DA6C";

ALTER TABLE DEVA_ARTIKEL_LOGBUCH DROP CONSTRAINT "FK14718296DC74F062";

ALTER TABLE DEVA_KOMPONENTE_KOMMENTAR DROP CONSTRAINT "FK3B7548ACDC74F062";

ALTER TABLE DEVA_ANGEMELDETER_BENUTZER DROP CONSTRAINT "FKDAE0E2B2DC74F062";

ALTER TABLE DEVA_BENUTZER_FIRMA DROP CONSTRAINT "FK805A2EB4DC74F062";

ALTER TABLE DEVA_BONUSZEIT DROP CONSTRAINT "FK4F4940824C4C8E48";

ALTER TABLE DEVA_ARTIKEL_KOMMENTAR DROP CONSTRAINT "FK792535B2DC74F062";

ALTER TABLE DEVA_ARTIKEL_V DROP CONSTRAINT "FK1B196950B2657C32";

ALTER TABLE DEVA_FIRMA_ANSPRECHPARTNER DROP CONSTRAINT "FK21484EB7D52DE102";

ALTER TABLE DEVA_BENUTZER_ROLLEN DROP CONSTRAINT "FK9FB79F15DC74F062";

ALTER TABLE DEVA_KOMPONENTE DROP CONSTRAINT "FKB8970B338C57DA6C";

ALTER TABLE JBPM_TASK DROP CONSTRAINT "FKB48F3A4F6CE1EF3A";

ALTER TABLE JBPM_ATTACHMENT DROP CONSTRAINT "FKF6BB126D8EF5F064";

ALTER TABLE JBPM_TASK DROP CONSTRAINT "FKB48F3A4FF213F8B5";

ALTER TABLE JBPM_TASK DROP CONSTRAINT "FKB48F3A4F9E619A0";

ALTER TABLE JBPM_TASK_COMMENT DROP CONSTRAINT "FKE7D49C4F2FF04688";

ALTER TABLE JBPM_PI_INFO_ET DROP CONSTRAINT "FK18A11EE46C397FD3";

ALTER TABLE JBPM_EMAIL_NOT_HEAD DROP CONSTRAINT "FKA84EA9991F7B912A";

ALTER TABLE DEVA_BENUTZER_ROLLEN DROP CONSTRAINT "FK9FB79F156273ABA8";

ALTER TABLE DEVA_ROLLE_PROZESS_SCHRITT DROP CONSTRAINT "FK3804709E6273ABA8";

ALTER TABLE DEVA_ROLLE_AMPELSTATUS DROP CONSTRAINT "FK511F24132E56239D";

ALTER TABLE DEVA_ROLLE_AKTIONS_B DROP CONSTRAINT "FK7C62E8EED1137703";

ALTER TABLE DEVA_ROLLE_SICHT_B DROP CONSTRAINT "FK714B612D1137703";

ALTER TABLE DEVA_FIRMA_LIEFERANTEN DROP CONSTRAINT "FKAB4BB876793F005B";

ALTER TABLE DEVA_FIRMA_LIEFERANTEN DROP CONSTRAINT "FKAB4BB876E53E3934";

ALTER TABLE DEVA_ARTIKEL DROP CONSTRAINT "FK6E9467B938FD1C19";

ALTER TABLE DEVA_BENUTZER DROP CONSTRAINT "FK129925F083E97000";

ALTER TABLE DEVA_KOMPONENTE DROP CONSTRAINT "FKB8970B33843549E2";

ALTER TABLE DEVA_PROZESSDEFINITION DROP CONSTRAINT "FKA2830F9838FD1C19";

ALTER TABLE DEVA_KOMPONENTE DROP CONSTRAINT "FKB8970B3338FD1C19";

ALTER TABLE DEVA_PROZESSDEFINITION DROP CONSTRAINT "FKA2830F98843549E2";

ALTER TABLE DEVA_FIRMA_SOLLZEITEN_K DROP CONSTRAINT "FK7CBC0ED65CF6CF14";

ALTER TABLE DEVA_BENUTZER_FIRMA DROP CONSTRAINT "FK805A2EB45B19B851";

ALTER TABLE DEVA_FIRMA_SOLLZEITEN_A DROP CONSTRAINT "FK7CBC0ECC5CF6CF14";

ALTER TABLE DEVA_FIRMA_ANSPRECHPARTNER DROP CONSTRAINT "FK21484EB75CF6CF14";

ALTER TABLE DEVA_ARTIKEL DROP CONSTRAINT "FK6E9467B9843549E2";

ALTER TABLE DEVA_ARTIKEL_FAHRZEUGE DROP CONSTRAINT "FKE6AB83FD2BF81BD0";

ALTER TABLE DEVA_DOKUMENT DROP CONSTRAINT "FKEE37CA061AD81661";

ALTER TABLE DEVA_DOKUMENT DROP CONSTRAINT "FKEE37CA06862116E3";

ALTER TABLE DEVA_ROLLE_PROZESS_SCHRITT DROP CONSTRAINT "FK3804709E75B486B9";

ALTER TABLE DEVA_PROZESS_SCHRITT DROP CONSTRAINT "FK7CF7493575B486B9";

ALTER TABLE DEVA_SOLLZEITEN DROP CONSTRAINT "FK31B0DBCE38FE1D3C";

ALTER TABLE DEVA_UEBERSETZUNG_PS DROP CONSTRAINT "FK96480738153E746F";

ALTER TABLE DEVA_UEBERSETZUNG_ZUBEHOER DROP CONSTRAINT "FK8B6A0F27ADEDE368";

ALTER TABLE DEVA_ZUBEHOER DROP CONSTRAINT "FK8B7D1A55E7B2276";

ALTER TABLE DEVA_ZUSATZINFORMATION DROP CONSTRAINT "FKC53A280ABB69726C";

ALTER TABLE DEVA_UEBERSETZUNG_ZINFO DROP CONSTRAINT "FK68899AB3D2732549";

ALTER TABLE DEVA_PRODUKTGRUPPE DROP CONSTRAINT "FKB68B59AF9315E404";

ALTER TABLE DEVA_UEBERSETZUNG_P DROP CONSTRAINT "FK4D9087B9315E404";

ALTER TABLE DEVA_KOMPONENTE DROP CONSTRAINT "FKB8970B33A8076CAC";

ALTER TABLE DEVA_UEBERSETZUNG_K DROP CONSTRAINT "FK4D908761DC451DA";

ALTER TABLE DEVA_ANGEMELDETER_BENUTZER DROP CONSTRAINT "FKDAE0E2B231ED32E7";

DROP TABLE JBPM_TASK_COMMENT CASCADE CONSTRAINTS;

DROP TABLE JBPM_SUBTASKSSTRATEGY CASCADE CONSTRAINTS;

DROP TABLE JBPM_RA_POTOWNERS CASCADE CONSTRAINTS;

DROP TABLE JBPM_PI_INFO_ET CASCADE CONSTRAINTS;

DROP TABLE JBPM_PA_STAKEHOLDERS CASCADE CONSTRAINTS;

DROP TABLE JBPM_PA_RECIPIENTS CASCADE CONSTRAINTS;

DROP TABLE JBPM_PA_POTOWNERS CASCADE CONSTRAINTS;

DROP TABLE JBPM_PA_EXCLOWNERS CASCADE CONSTRAINTS;

DROP TABLE JBPM_PA_BAS CASCADE CONSTRAINTS;

DROP TABLE JBPM_NOTIFICATION CASCADE CONSTRAINTS;

DROP TABLE JBPM_I18NTEXT CASCADE CONSTRAINTS;

DROP TABLE JBPM_EMAIL_NOT_HEAD CASCADE CONSTRAINTS;

DROP TABLE JBPM_DELEGATION_DELEGATES CASCADE CONSTRAINTS;

DROP TABLE JBPM_BOOLEAN_EXPRESSION CASCADE CONSTRAINTS;

DROP TABLE JBPM_ATTACHMENT CASCADE CONSTRAINTS;

DROP TABLE DEVA_UEBERSETZUNG_ZUBEHOER CASCADE CONSTRAINTS;

DROP TABLE DEVA_UEBERSETZUNG_ZINFO CASCADE CONSTRAINTS;

DROP TABLE DEVA_UEBERSETZUNG_PS CASCADE CONSTRAINTS;

DROP TABLE DEVA_UEBERSETZUNG_P CASCADE CONSTRAINTS;

DROP TABLE DEVA_UEBERSETZUNG_K CASCADE CONSTRAINTS;

DROP TABLE DEVA_UEBERSETZUNG_ARTIKEL CASCADE CONSTRAINTS;

DROP TABLE DEVA_SOLLZEITEN_KLASSIFIKATION CASCADE CONSTRAINTS;

DROP TABLE DEVA_SOLLZEIT_WDH_K CASCADE CONSTRAINTS;

DROP TABLE DEVA_ROLLE_SICHT_B CASCADE CONSTRAINTS;

DROP TABLE DEVA_ROLLE_PROZESS_SCHRITT CASCADE CONSTRAINTS;

DROP TABLE DEVA_ROLLE_AMPELSTATUS CASCADE CONSTRAINTS;

DROP TABLE DEVA_ROLLE_AKTIONS_B CASCADE CONSTRAINTS;

DROP TABLE DEVA_KOMPONENTE_ZINFO CASCADE CONSTRAINTS;

DROP TABLE DEVA_KOMPONENTE_V CASCADE CONSTRAINTS;

DROP TABLE DEVA_KOMPONENTE_LOGBUCH CASCADE CONSTRAINTS;

DROP TABLE DEVA_KOMPONENTE_KOMMENTAR CASCADE CONSTRAINTS;

DROP TABLE DEVA_KOMPONENTE_DOKUMENTE CASCADE CONSTRAINTS;

DROP TABLE DEVA_FIRMA_SOLLZEITEN_K CASCADE CONSTRAINTS;

DROP TABLE DEVA_FIRMA_SOLLZEITEN_A CASCADE CONSTRAINTS;

DROP TABLE DEVA_FIRMA_LIEFERANTEN CASCADE CONSTRAINTS;

DROP TABLE DEVA_FIRMA_ANSPRECHPARTNER CASCADE CONSTRAINTS;

DROP TABLE DEVA_BPMN_DEFINITION_THN CASCADE CONSTRAINTS;

DROP TABLE DEVA_BONUSZEIT CASCADE CONSTRAINTS;

DROP TABLE DEVA_BENUTZER_ROLLEN CASCADE CONSTRAINTS;

DROP TABLE DEVA_BENUTZER_PRODUKTGRUPPE CASCADE CONSTRAINTS;

DROP TABLE DEVA_BENUTZER_FIRMA CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL_ZUBEHOER CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL_ZINFO CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL_V CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL_LOGBUCH CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL_KOMPONENTE CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL_KOMMENTAR CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL_FAHRZEUGE CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL_DOKUMENTE CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL_BESTANDTEIL CASCADE CONSTRAINTS;

DROP TABLE DEVA_ANGEMELDETER_BENUTZER CASCADE CONSTRAINTS;

DROP TABLE DEVA_ARTIKEL CASCADE CONSTRAINTS;

DROP TABLE DEVA_KOMPONENTE CASCADE CONSTRAINTS;

DROP TABLE JBPM_TASK CASCADE CONSTRAINTS;

DROP TABLE DEVA_PROZESS CASCADE CONSTRAINTS;

DROP TABLE DEVA_PROZESS_SCHRITT CASCADE CONSTRAINTS;

DROP TABLE JBPM_REASSIGNMENT CASCADE CONSTRAINTS;

DROP TABLE JBPM_ESCALATION CASCADE CONSTRAINTS;

DROP TABLE JBPM_DEADLINE CASCADE CONSTRAINTS;

DROP TABLE DEVA_PROZESSDEFINITION CASCADE CONSTRAINTS;

DROP TABLE DEVA_PRODUKTGRUPPE CASCADE CONSTRAINTS;

DROP TABLE DEVA_DOKUMENT CASCADE CONSTRAINTS;

DROP TABLE JBPM_EMAIL_NOT CASCADE CONSTRAINTS;

DROP TABLE DEVA_ZUSATZINFORMATION CASCADE CONSTRAINTS;

DROP TABLE DEVA_ZUBEHOER CASCADE CONSTRAINTS;

DROP TABLE DEVA_SOLLZEITEN CASCADE CONSTRAINTS;

DROP TABLE DEVA_BPMNDEFINITION CASCADE CONSTRAINTS;

DROP TABLE DEVA_BEZEICHNUNG_ARTIKEL CASCADE CONSTRAINTS;

DROP TABLE DEVA_BENUTZER CASCADE CONSTRAINTS;

DROP TABLE JBPM_USER CASCADE CONSTRAINTS;

DROP TABLE JBPM_PI_INFO CASCADE CONSTRAINTS;

DROP TABLE JBPM_EMAIL_HEADER CASCADE CONSTRAINTS;

DROP TABLE DEVA_ROLLE CASCADE CONSTRAINTS;

DROP TABLE DEVA_FIRMA CASCADE CONSTRAINTS;

DROP TABLE DEVA_FAHRZEUG_BEZEICHNUNG CASCADE CONSTRAINTS;

DROP TABLE DEVA_DOKUMENT_BINAERDATEN CASCADE CONSTRAINTS;

DROP TABLE DEVA_BEZEICHUNG_PS CASCADE CONSTRAINTS;

DROP TABLE DEVA_BEZEICHNUNG_ZUBEHOER CASCADE CONSTRAINTS;

DROP TABLE DEVA_BEZEICHNUNG_ZINFO CASCADE CONSTRAINTS;

DROP TABLE DEVA_BEZEICHNUNG_PRODUKTGRUPPE CASCADE CONSTRAINTS;

DROP TABLE DEVA_BEZEICHNUNG_KOMPONENTE CASCADE CONSTRAINTS;

DROP TABLE DEVA_BENUTZER_LISTE CASCADE CONSTRAINTS;

DROP TABLE JBPM_PROCESSINSTANCE_EVENTINFO CASCADE CONSTRAINTS;

DROP TABLE JBPM_NOTIFICATION_RECIPIENTS CASCADE CONSTRAINTS;

DROP TABLE JBPM_NOTIFICATION_BAS CASCADE CONSTRAINTS;

DROP TABLE JBPM_GROUP CASCADE CONSTRAINTS;

DROP TABLE JBPM_CONTENT CASCADE CONSTRAINTS;

DROP TABLE FOO CASCADE CONSTRAINTS;

DROP TABLE DROOLS_WORKITEMINFO CASCADE CONSTRAINTS;

DROP TABLE DROOLS_SESSIONINFO CASCADE CONSTRAINTS;

DROP TABLE DEVA_FAELLIGKEITEN CASCADE CONSTRAINTS;

